# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: "/src"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: FluentAssertions
        update-types:
          - version-update:semver-major
      - dependency-name: FluentValidation
        update-types:
          - version-update:semver-major
    groups:
      nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/packaging/cloudron"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      cloudron-docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
