#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring BookshelfNG files to be backed up..."

### ynh_backup declares the paths to include. YunoHost copies them after this
### script completes, which also lets it report backup progress correctly.

#=================================================
# BACKUP THE DATA DIR
#=================================================
ynh_backup "$data_dir"

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_backup "$install_dir"

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info "Backup script completed for $app. (YunoHost will then copy the declared files to the archive)."
