#!/bin/bash

source _common.sh

ynh_script_progression "Updating BookshelfNG's reverse proxy and URL base..."
bookshelfng_prepare_service
ynh_systemctl --service="$app" --action="restart"
bookshelfng_register_service

ynh_script_progression "BookshelfNG URL update completed"
