#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX AND SYSTEMD CONFIGURATION
#=================================================
ynh_script_progression "Updating BookshelfNG's reverse proxy and URL base..."

bookshelfng_prepare_service
ynh_systemctl --service="$app" --action="restart"
bookshelfng_register_service

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "BookshelfNG URL update completed"
