#!/bin/bash

source _common.sh

ynh_script_progression "Stopping BookshelfNG..."
ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Installing the pinned BookshelfNG release..."
ynh_setup_source --dest_dir="$install_dir" --source_id="main" --full_replace=1
chown -R "$app:$app" "$install_dir"

ynh_script_progression "Refreshing the service and reverse proxy..."
bookshelfng_prepare_service

ynh_script_progression "Starting BookshelfNG..."
bookshelfng_start_service
bookshelfng_register_service

ynh_script_progression "BookshelfNG upgrade completed"
