// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authorGroup': string;
  'conflict': string;
  'error': string;
  'fileList': string;
  'fileRow': string;
  'fileStatus': string;
  'moreFiles': string;
  'moveButton': string;
  'notices': string;
  'pathArrow': string;
  'pathLabel': string;
  'pathSummary': string;
  'queued': string;
  'spaceSummary': string;
  'summary': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
